package com.honganjk.ynybzbizfood.utils.http.download;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

import com.honganjk.ynybzbizfood.utils.db.LiteOrmUtil;

import java.util.List;

/**
 * DAO for table "download".
 */
public class DownloadDao {

    public DownloadEntity queryById(String id) {
        return LiteOrmUtil.getLiteOrm().queryById(id, DownloadEntity.class);
    }

    public List<DownloadEntity> queryAll() {
        return LiteOrmUtil.getLiteOrm().query(DownloadEntity.class);
    }

    public void save(Object entity) {
        LiteOrmUtil.getLiteOrm().save(entity);
    }

    public void update(Object entity) {
        LiteOrmUtil.getLiteOrm().update(entity);
    }

    public void delete(Object entity) {
        LiteOrmUtil.getLiteOrm().delete(entity);
    }
}
